import type { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    name: "Crimson Silk Saree",
    category: "Saree",
    gender: "Women",
    size: "Free Size",
    color: "Crimson",
    fabric: "Silk",
    occasion: "Wedding",
    stock: 15,
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "2",
    name: "Royal Blue Lehenga",
    category: "Lehenga",
    gender: "Women",
    size: "M",
    color: "Royal Blue",
    fabric: "Velvet",
    occasion: "Festival",
    stock: 8,
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "3",
    name: "Classic White Kurta",
    category: "Kurta",
    gender: "Men",
    size: "L",
    color: "White",
    fabric: "Cotton",
    occasion: "Casual",
    stock: 30,
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "4",
    name: "Golden Border Dhoti",
    category: "Dhoti",
    gender: "Men",
    size: "Free Size",
    color: "Cream",
    fabric: "Silk Blend",
    occasion: "Wedding",
    stock: 22,
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "5",
    name: "Green Georgette Saree",
    category: "Saree",
    gender: "Women",
    size: "Free Size",
    color: "Green",
    fabric: "Georgette",
    occasion: "Formal",
    stock: 18,
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "6",
    name: "Embroidered Kurta",
    category: "Kurta",
    gender: "Men",
    size: "XL",
    color: "Black",
    fabric: "Linen",
    occasion: "Festival",
    stock: 12,
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "7",
    name: "Pastel Pink Lehenga",
    category: "Lehenga",
    gender: "Women",
    size: "S",
    color: "Pastel Pink",
    fabric: "Net",
    occasion: "Wedding",
    stock: 5,
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "8",
    name: "Casual Cotton Kurta",
    category: "Kurta",
    gender: "Women",
    size: "M",
    color: "Yellow",
    fabric: "Cotton",
    occasion: "Casual",
    stock: 40,
    imageUrl: "https://placehold.co/600x400.png",
  },
];
